version: '3.8'

services:
  feuerprofi:
    build: .
    container_name: feuerprofi_app
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Europe/Berlin
      - SEQ_SERVER_URL=${SEQ_SERVER_URL:-}
      - SEQ_API_KEY=${SEQ_API_KEY:-}
